name: Deploy to GitHub Pages

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Debug Secrets
        run: |
          echo "Longitud de GEMINI_API_KEY: ${#SECRET_GEMINI}"
          echo "Longitud de WEB3FORMS_KEY: ${#SECRET_WEB3}"
        env:
          SECRET_GEMINI: ${{ secrets.VITE_GEMINI_API_KEY }}
          SECRET_WEB3: ${{ secrets.VITE_WEB3FORMS_ACCESS_KEY }}

      - name: Hardcode API Key into source code
        env:
          SECRET_GEMINI: ${{ secrets.VITE_GEMINI_API_KEY }}
        run: |
          sed -i "s/REPLACE_ME_GEMINI_API_KEY/$SECRET_GEMINI/g" src/lib/gemini.ts

      - name: Inject Secrets into .env
        env:
          SECRET_GEMINI: ${{ secrets.VITE_GEMINI_API_KEY }}
          SECRET_WEB3: ${{ secrets.VITE_WEB3FORMS_ACCESS_KEY }}
        run: |
          echo "VITE_GEMINI_API_KEY=$SECRET_GEMINI" >> .env
          echo "VITE_WEB3FORMS_ACCESS_KEY=$SECRET_WEB3" >> .env
          echo "VITE_BASE_PATH=/base_react_2026/" >> .env

      - name: Build
        run: npm run build
        env:
          VITE_BASE_PATH: /base_react_2026/
          VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY }}
          VITE_WEB3FORMS_ACCESS_KEY: ${{ secrets.VITE_WEB3FORMS_ACCESS_KEY }}
          
      - name: Generate 404 fallback for SPA
        run: cp ./dist/index.html ./dist/404.html
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
